# Generated by Django 5.2.7 on 2025-10-16 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='specie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
